- name: 安装 haproxy
  yum:
      state: present 
      name: haproxy
- name: 复制 haproxy.cfg
  template:
          src: haproxy.cfg.j2
          dest: /etc/haproxy/haproxy.cfg
- name: 运行 haproxy
  service:
         name: haproxy
         state: started 
         enabled: true
		 
- name: 解压文件
  unarchive: 
           src: /tmp/keepalived-2.0.2.tar.gz
           dest: /tmp 
           copy: no

- name: 复制检测脚本文件
  copy:
      src: check_haproxy.sh
      dest: /etc/keepalived/
      mode: 755
- name: 复制安装脚本文件
  copy:
      src: install.sh
      dest: /tmp
      mode: 755

- name: 配置并运行 keepalived
  shell: /bin/bash /tmp/install.sh
