- name: 复制 flannel 压缩文件
  copy: 
      src: /root/flannel-{{ flannel_version }}-linux-amd64.tar.gz
      dest: /{{ remote_dir }}/flannel-{{ flannel_version }}-linux-amd64.tar.gz
- name: 解压文件
  unarchive: 
           src: /{{ remote_dir }}/flannel-{{ flannel_version }}-linux-amd64.tar.gz 
           dest: /{{ remote_dir }}
           copy: no

- name: 复制 flanneld
  command: cp /{{ remote_dir }}/flanneld  /usr/bin/
- name: 新建目录
  file: 
      path: /usr/libexec/flannel/
      state: directory

- name: 复制 mk-docker-opts.sh
  command: cp /{{ remote_dir }}/mk-docker-opts.sh  /usr/libexec/flannel/
- name: 复制 flannel 启动项
  template:
          src: flanneld.service.j2
          dest: /usr/lib/systemd/system/flanneld.service

- name: 复制 flanneld-start
  template:
          src: flanneld-start.j2
          dest: "{{ bin_dir }}/flanneld-start"
          mode: 755

- name: 复制 flannel 配置文件
  template:
          src: flanneld.j2
          dest: /etc/sysconfig/flanneld

- name: 复制 docker 启动项
  template:
          src: docker.service.j2
          dest: /usr/lib/systemd/system/docker.service
          
- name: 复制 docker 启动项
  template:
          src: docker.service.j2
          dest: /usr/lib/systemd/system/docker.service

- name: 重载
  command: systemctl daemon-reload

- name: 启动 flannel
  service:
          name: flanneld
          state: started
          enabled: yes

- name: 重启 docker
  service:
          name: docker
          state: restarted
          enabled: yes
